name: Build ZMK firmware
on:
  workflow_dispatch:
  pull_request:
  push:
    paths:
      - ".github/workflows/build.yml"
      - "build.yaml"
      - "config/*.keymap"
      - "config/*.dtsi"
      - "config/*.conf"
      - "config/west.yml"
      - "boards/*/*/*.keymap"
      - "boards/shields/silakka54/**"

jobs:
  build:
    uses: zmkfirmware/zmk/.github/workflows/build-user-config.yml@v0.3
